### ISSUE TITLE
Screenshot in Gods Eater

### ISSUE THREAD

**Issue by wickedsick** [codestation/prxshot#1]
Reporting that the plugin do not take SS in Gods Eater, the plugin do create a folder for the game, but do not take screenshot.
Another game, Um Jammer Lammy (PSN release) the plugin do not create a folder nor take any ss. 
Tested under 6.39 ME-2 Phat 1001 with prxshot and prxshot++

Albeit everything else seems to be normal.

**Comment by codestation** [comment]
Try again with the debug version:
C version: https://github.com/downloads/codestation/prxshot/prxshot.prx
C++ version: https://github.com/downloads/codestation/prxshot/prxshot++.prx
and attach the resulting log (prxshot.log) so i can see where is the problem.
Also i need a list of your activated plugins in game.txt.

**Comment by wickedsick** [comment]
OK, I've tested booth of them, same results. Here are the log file for the prxshot++:

PRXshot start
Creating heap of 16 KiB
Starting Screenshot thread
ScreenshotThread started
Settings loaded
Loading PbpBlock
Loading PBP/SFO
PbpBlock::load, (null)
Loading: disc0:/PSP_GAME/PARAM.SFO
calling createScreenshotDir
Shot_path: ms0:/PSP/SCREENSHOT/ULUS10563, format: %s/pic_%04d.bmp
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0000.bmp as name
Starting loop
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0001.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0002.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0003.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0004.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0005.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0006.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0007.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0008.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0009.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0010.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0011.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0012.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0013.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0014.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0015.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0016.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0017.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
PRXshot start
Creating heap of 16 KiB
Starting Screenshot thread
ScreenshotThread started
Settings loaded
Loading PbpBlock
Loading PBP/SFO
PbpBlock::load, (null)
Loading: ms0:/seplugins/prxshot/xmb.sfo
calling createScreenshotDir
Shot_path: ms0:/PSP/SCREENSHOT/XMB, format: %s/pic_%04d.bmp
Using ms0:/PSP/SCREENSHOT/XMB/pic_0000.bmp as name
Starting loop
PRXshot start
Creating heap of 16 KiB
Starting Screenshot thread
ScreenshotThread started
Settings loaded
Loading PbpBlock
Loading PBP/SFO
PbpBlock::load, (null)
Loading: ms0:/seplugins/prxshot/xmb.sfo
calling createScreenshotDir
Shot_path: ms0:/PSP/SCREENSHOT/XMB, format: %s/pic_%04d.bmp
Using ms0:/PSP/SCREENSHOT/XMB/pic_0000.bmp as name
Starting loop
PRXshot start
Creating heap of 16 KiB
Starting Screenshot thread
ScreenshotThread started
Settings loaded
Loading PbpBlock
Loading PBP/SFO
PbpBlock::load, (null)
Loading: disc0:/PSP_GAME/PARAM.SFO
calling createScreenshotDir
Shot_path: ms0:/PSP/SCREENSHOT/ULUS10563, format: %s/pic_%04d.bmp
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0000.bmp as name
Starting loop
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0001.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
opening (null)
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0002.bmp as name
pbp: (null), sfo: ms0:/seplugins/prxshot/, pic0 size: 753008056 bytes
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0003.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0004.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0005.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0006.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0007.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0008.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0009.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0010.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0011.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0012.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0013.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0014.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0015.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0016.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0017.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0018.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0019.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0020.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0021.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0022.bmp as name
Taking screenshot
Allocating 391734 bytes from kernel memory
Allocating block from volatile
Using ms0:/PSP/SCREENSHOT/ULUS10563/pic_0023.bmp as name
PRXshot start
Creating heap of 16 KiB
Starting Screenshot thread
ScreenshotThread started
Settings loaded
Loading PbpBlock
Loading PBP/SFO
PbpBlock::load, (null)
Loading: ms0:/seplugins/prxshot/xmb.sfo
calling createScreenshotDir
Shot_path: ms0:/PSP/SCREENSHOT/XMB, format: %s/pic_%04d.bmp
Using ms0:/PSP/SCREENSHOT/XMB/pic_0000.bmp as name
Starting loop

The log file for the prxshot:

Taking screenshot
Allocating 391734 bytes from kernel memory
Using ms0:/PSP/SCREENSHOT/XMB/pic_0001.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/XMB/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Using ms0:/PSP/SCREENSHOT/XMB/pic_0002.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/XMB/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Using ms0:/PSP/SCREENSHOT/XMB/pic_0003.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/XMB/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Using ms0:/PSP/SCREENSHOT/XMB/pic_0004.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/XMB/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Using ms0:/PSP/SCREENSHOT/XMB/pic_0005.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/XMB/PSCM.DAT
Taking screenshot
Allocating 391734 bytes from kernel memory
Using ms0:/PSP/SCREENSHOT/XMB/pic_0006.bmp as name
Starting pbp thread
Started PbpBlock thread
opening ms0:/PSP/SCREENSHOT/XMB/PSCM.DAT

> > > > > > > > > > > > > > > > > PRXshot started
> > > > > > > > > > > > > > > > > PRXshot main thread started
> > > > > > > > > > > > > > > > > Booting from UMD
> > > > > > > > > > > > > > > > > Init mode: Game
> > > > > > > > > > > > > > > > > Read ScreenshotKey: 00800000
> > > > > > > > > > > > > > > > > Read KeyTimeout: 00000000
> > > > > > > > > > > > > > > > > Read ScreenshotName: %s/pic_%04d.bmp
> > > > > > > > > > > > > > > > > Read XMBClearCache: 0
> > > > > > > > > > > > > > > > > Entering screenshot loop
> > > > > > > > > > > > > > > > > Trying to open disc0:/UMD_DATA.BIN
> > > > > > > > > > > > > > > > > UMD/ISO found
> > > > > > > > > > > > > > > > > Got custom key button for ULUS10563: 00800000
> > > > > > > > > > > > > > > > > Got custom key timeout for ULUS10563: 0
> > > > > > > > > > > > > > > > > Directory doesn't exists or is outdated
> > > > > > > > > > > > > > > > > Creating base directory ms0:/PSP/SCREENSHOT
> > > > > > > > > > > > > > > > > Creating directory ms0:/PSP/SCREENSHOT/ULUS10563
> > > > > > > > > > > > > > > > > New screenshot dir created, new pbp needed
> > > > > > > > > > > > > > > > > Taking shot: ms0:/PSP/SCREENSHOT/ULUS10563/pic_0000.bmp
> > > > > > > > > > > > > > > > > Screenshot fail
> > > > > > > > > > > > > > > > > pbp_thread_start called
> > > > > > > > > > > > > > > > > Trying to open ms0:/PSP/SCREENSHOT/ULUS10563/PSCM.DAT
> > > > > > > > > > > > > > > > > UMD found, opening disc0:/PSP_GAME/PARAM.SFO
> > > > > > > > > > > > > > > > > Starting PSCM.DAT creation
> > > > > > > > > > > > > > > > > Got SFO size: 560 bytes
> > > > > > > > > > > > > > > > > Reading SFO
> > > > > > > > > > > > > > > > > Taking shot: ms0:/PSP/SCREENSHOT/ULUS10563/pic_0001.bmp
> > > > > > > > > > > > > > > > > Screenshot fail
> > > > > > > > > > > > > > > > > Taking shot: ms0:/PSP/SCREENSHOT/ULUS10563/pic_0002.bmp
> > > > > > > > > > > > > > > > > Screenshot fail
> > > > > > > > > > > > > > > > > Taking shot: ms0:/PSP/SCREENSHOT/ULUS10563/pic_0003.bmp
> > > > > > > > > > > > > > > > > Screenshot fail
> > > > > > > > > > > > > > > > > Taking shot: ms0:/PSP/SCREENSHOT/ULUS10563/pic_0004.bmp
> > > > > > > > > > > > > > > > > Screenshot fail
> > > > > > > > > > > > > > > > > PRXshot start
> > > > > > > > > > > > > > > > > Creating heap of 16 KiB
> > > > > > > > > > > > > > > > > Starting Screenshot thread
> > > > > > > > > > > > > > > > > ScreenshotThread started
> > > > > > > > > > > > > > > > > Settings loaded
> > > > > > > > > > > > > > > > > Loading PbpBlock
> > > > > > > > > > > > > > > > > Loading PBP/SFO
> > > > > > > > > > > > > > > > > PbpBlock::load, (null)
> > > > > > > > > > > > > > > > > Loading: ms0:/seplugins/prxshot/xmb.sfo
> > > > > > > > > > > > > > > > > calling createScreenshotDir
> > > > > > > > > > > > > > > > > Shot_path: ms0:/PSP/SCREENSHOT/XMB, format: %s/pic_%04d.bmp
> > > > > > > > > > > > > > > > > Using ms0:/PSP/SCREENSHOT/XMB/pic_0000.bmp as name
> > > > > > > > > > > > > > > > > Starting loop
> > > > > > > > > > > > > > > > > PRXshot start
> > > > > > > > > > > > > > > > > Creating heap of 16 KiB
> > > > > > > > > > > > > > > > > Starting Screenshot thread
> > > > > > > > > > > > > > > > > ScreenshotThread started
> > > > > > > > > > > > > > > > > Settings loaded
> > > > > > > > > > > > > > > > > Loading PbpBlock
> > > > > > > > > > > > > > > > > Loading PBP/SFO
> > > > > > > > > > > > > > > > > PbpBlock::load, (null)
> > > > > > > > > > > > > > > > > Loading: ms0:/seplugins/prxshot/xmb.sfo
> > > > > > > > > > > > > > > > > calling createScreenshotDir
> > > > > > > > > > > > > > > > > Shot_path: ms0:/PSP/SCREENSHOT/XMB, format: %s/pic_%04d.bmp
> > > > > > > > > > > > > > > > > Using ms0:/PSP/SCREENSHOT/XMB/pic_0000.bmp as name
> > > > > > > > > > > > > > > > > Starting loop

And my game.txt:

ms0:/seplugins/prxshot/prxshot.prx 1
ms0:/seplugins/AdhocToUSB.prx 1

Only have those two.

**Comment by codestation** [comment]
Seeing the log looks like the AdhocToUSB is using almost all of the kernel memory so prxshot cannot allocate the ~382KiB of memory needed to store the bitmap in memory. Since you are using a PSP1000 the umd cache isn't available, so prxshot tries to use the volatile memory as a last resort but it fails again (either the usb modules or the game has already a lock for the volatile mem) so prxshot cannot take the picture.

Since prxshot works on-the-fly it needs that amount of memory so it doesn't need to pause the game. I cannot do much about it because the PSP1000 is too limited in memory so your only option could be disabling that plugin.

The only thing that i can do for PSP1000 users facing this problem is to offer a compatibility mode to pause the game while taking the screenshot (and yes, pausing the game while playing online can lead to dropouts but there isn't much that i can do for PSP1000 users), so the plugin doesn't require an intermediate buffer.

**Comment by wickedsick** [comment]
Yes. After disabling the AdhocToUSB, Gods Eater took some SS indeed. So it's more a hardware issue 
and therefore beyond anything you can do make it work as it is, without freezing the game I mean 
):

But, why the prxshot doesn't work with Um Jammer Lammy or Final Fantasy 7, both PSN releases? May it be the plugin do not support, somehow, games when they are in PSP/GAME?

**Comment by wickedsick** [comment]
Also, and what if the screenshots are taken in another format? As like in .jpg?
